#+OPTIONS: \n:t
# Note: Above OPTION is not working on site like github
* MacOS (Catalina)
** Basic setup
   - basic setup like keyboard, click, mouse...
** HomeBrew
  Mac Setup start from install home brew:
#+begin_src sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#+end_src
  Common homebrew command:
  #+begin_src sh
brew list
brew cask list
brew install <package>
brew uninstall <package>
  #+end_src
** Terminal and VIM
   ~iTerm2~ is the most popular chice in macOS as Terminal Emulater. Install it through ~brew install item2~.
** Add $PATH
#+begin_src sh
  # vim /etc/path.d/dev.public <-- any name should be OK
  /Users/jesse23/u/dev/macOS/bin
  /Users/jesse23/u/dex/bin
#+end_src
    This is a L2 desc.
    \\
    Try if CR works fine
   
 Hello!
* Github org mode support
  - https://github.com/fniessen/refcard-org-mode
  - https://github.com/novoid/github-orgmode-tests/blob/master/README.org

* Test
#+begin_quote
Let us change our traditional attitude to the construction of programs:
Instead of imagining that our main task is to instruct a computer what to do,
let us concentrate rather on explaining to human beings what we want a
computer to do.

The practitioner of literate programming can be regarded as an essayist, whose
main concern is with exposition and excellence of style. Such an author, with
thesaurus in hand, chooses the names of variables carefully and explains what
each variable means. He or she strives for a program that is comprehensible
because its concepts have been introduced in an order that is best for human
understanding, using a mixture of formal and informal methods that reinforce
each other.

-- Donald Knuth
#+end_quote
what is verse?
#+begin_verse
Everything should be made as simple as possible,
but not any simpler. -- Albert Einstein
#+end_verse
this is code:
#+BEGIN_SRC sh
   git add *
   git add -u
   git commit
   git push
   git pull
#+END_SRC
